== Basic Programming Concepts

=== Variables and Types

What is a variable?
It is a named space in a computer memory where you can store data, and also retrive that data later.
An example of variables: x, y, speed, temperature, energy, name

What is a type of a variable?
Type of a variable determines what kind of data can be stored in some variable - for example: numbers or letters.




Create analogy of cars ??
I would go with animals or Vehicles. 
Cars do not differ much in some general elements.

=== Class

Classes are basic building blocks of a Java programme. Every Java programme consists of a number of classes.
Every class holds some data (variables which are called class fields) and some operations with that data which are  called methods.
Class is also a kind of variable type, for special kind of variables called objects.

==== Methods
A method is a set of instructions that can be 'called' from some other place in programme. 
After these instructions get executed, program execution continues from the place where method was called.
Methods can accept some data as an input, and they can also return some data as their result (but they dont have to)


And also Objects


==== Constructors

Constructor is a special kind of method that get executed when the object is created. 
This special mathod takes care of an object initialization - setting initial values to its fields.


=== Package

Its simply a folders where classes are stored.

. org.devoxx4kids.java.cars.vw
. org.devoxx4kids.java.cars.lexus
. org.devoxx4kids.java.cars.honda

=== Types

==== Primitive types

==== Boxed types
I think this can confuse them here

==== Autoboxing and unboxing

Introduce primitive and boxed types

. color
. how many doors ?
. convertible ?
. automatic or manual ?

=== Access Modifiers

=== Methods

. drive
. brake
. turn

=== Operators

=== Arrays

rich people have too many cars

=== public static void main

=== Annotations

=== Comments

