== Basic Programming Concepts

=== Types

Variables are pieces of information that our program can use.  If we look back
to our example from the introduction, we could have used a variable:

----
    public class Devoxx4kids {
        public static void main(String[] args) {
            String statement = "Java is fun! :)";
            System.out.println(statement);
        }
    }
----

In the first line of the main method, we *declare* a variable named "statement",
and *initialize* it (assign a value to it).  This allows us to refer to this
variable in the second line.

In the declaration, we must say what "type" the variable is.  In Java, all
variables have a type.  Our "statement" variable is of "String" type.

==== Primitive types

Java has some built in types called primitives. They include numbers, which
can be `byte`, `short`, `int`, `long`, `float`, or `double`. There are also
`boolean` primitives, which are a special type that can mean either 'true' or
'false' (think Yes and No), and finally there is a primitive type `char`,
which is just a single letter, like "a" or "b".

----
    byte smallestNumber;
    short smallNumber;
    int number;
    long bigNumber;
    float decimalNumber;
    double bigDecimalNumber;
    boolean yesOrNo;
    char letter;
    String text;
----

`byte`, `short`, `int`, and `long` can only store whole numbers, like 1, or 10
 or -5.  The difference is in how large the numbers can be - bytes can only be
between -128 and 127, whereas longs can be between -2^63^ and 2^63^-1 (which is
another way to write "9,223,372,036,854,775,807", a very large number!). `int`
is the most commonly used whole number type.

`float` and `double` can hold decimal numbers, like 2.5, or 10.0, or -0.5. The
difference is that `double` can have more numbers after the decimal point than
a `float` can. `double` is the usual choice between them.

We will mostly be using `int`, `double`, and `boolean` from these types. We will
also be using the type `String`, which is not a true "primitive" in Java, but is
very commonly used and useful.

===== Literals

Primitive types do not always need a variable.  It is also possible to include
values directly in the source code.  These values are called *literal*s.  For
number types, you can simply use numbers like `123`.  For boolean literals the
keywords `true` and `false` can be used.  `char` literals must have single
quotation marks surrounding them, like `'a'`.  String literals can be written
with double quotes, such as `"Hello!"`.

==== Classes

All other types in Java are Classes.  This includes types from the JDK class
library, but it is also how we can create custom types for our program.   So
far, we have defined one class, called Devoxx4kids.

----
    public class Devoxx4kids {

    }
----

In most cases, each class is defined in its own source code file.  We can add
more classes by creating new files, named after the class we are putting inside
them. Let's make a new class called Person, and put it inside a new file named
Person.java.

----
    public class Person {

    }
----

Now that we have two different Java files, compiling and running our program
is a little different.

----
    javac Devoxx4kids.java Person.java
    java Devoxx4kids
----

We have to give all of the names of our Java files to javac, but we only give
the name of the one with our main method to java.

Classes can contain both *variables* and *methods*.

1. Variables are things that a class *has*.
2. Methods are things that a class *does*.

We have seen one method already, the "main" method.  We have seen a variable
contained within that method, but variables can also be declared outside of a
method; these variables can be referred to by any method in that class.  Let's
modify our Devoxx4kids program to show what this looks like.

----
    public class Devoxx4kids {
        static String statement = "Java is fun! :)";

        public static void main(String[] args) {
            printStatement();
        }

        public static void printStatement() {
            System.out.println(statement);
        }
    }
----

In the case of our Person class, we can *have* a first name, a last name, and
an age, and we can *do* the action of introducing ourselves.  Notice that
both where we declare this `printStatement()` method and when we use (or
*call*) it, we use the brackets, `()` at the end; this will be explained
better later on.

----
    public class Person {
        String firstName;
        String lastName;
        int age;

        public void introduce() {
            System.out.println("Hi! My name is " + firstName + " " + lastName + ". I am " + age + " years old. I think Java is fun! :)");
        }
    }
----

Notice that the the variables and methods of the Person class do not use the
`static` keyword.  This keyword indicates that something belongs to the class
itself.  Without the `static` keyword, variables and methods belong to an
*instance* of the class.  This means that in order to use these variables
and methods, we must declare a *variable* of that *type*.  Let's change our
example program to see how this looks.

----
    public class Devoxx4kids {

        public static void main(String[] args) {
            Person p = new Person();
            p.firstName = "Mr.";
            p.lastName = "Java";
            p.age = 10;
            p.introduce();
        }
    }
----

Here we used a special method "Person()", called a *constructor*.  We'll
talk more about this, and methods in general, later.

If we had used the `static` keyword, we could have left out the line with
the constructor, and used the class name instead of the variable name in
the rest of the program.

----
    public class Devoxx4kids {

        public static void main(String[] args) {
            Person.firstName = "Mr.";
            Person.lastName = "Java";
            Person.age = 10;
            Person.introduce();
        }
    }
----

However, you can probably see how it is more useful to have an *instance*
of the Person class.  Static variables effectively belong to all instances
of the class.  Can you imagine if you and all of your classmates had the
same name?

==== Arrays

Arrays are a special sort of type. An array allows you to have a variable
that is actually a list with other nameless variables inside it. Making an
array variable is just like making a normal variable, but you add square
brackets, `[` and `]`.  If you want to refer to these nameless variables,
you must use the array variable name along with square brackets containing
a number.  That number is called the *index*.  Here, we declare an array
of type `int`, containing two nameless int variables, and assign those
variables using the *index*.  Notice that the first index we use is "0".
This is how all arrays work.  It also means that the largest index for
an array is actually one number lower than the size of the array.

----
    int[] numbers = new int[2];
    numbers[0] = 10;
    numbers[1] = 3;
----

Notice how making an array variable looks different from making a normal
variable. The 'new' keyword is used, and there are square brackets on both
side of the = . Inside the second pair of square brackets, you put the size
of the array, which here is two.

We use a primitive type "int" in this example, but it is also possible to
make arrays of other types.

One last thing to remember about array variables is that, in a single
array, all of the nameless variables (sometimes called *elements*) must
be of a matching type.

=== Comments

Comments allow programmers to add notes to a program. The notes don't do anything
in the program, but they can make it easier for other programmers to understand
what is happening. There are two ways to write comments in Java, and both are shown
in the example below.

----
    // The next two lines contain both code and comments
    boolean hasCat = true; // do I have a cat?
    boolean hasDog = true; // do I have a dog?

    /* if I have either a dog or a cat, then
       I have a pet! */
    boolean hasPet = hasCat || hasDog;
----

You can add a single line comment by starting with `//`.  In fact, you can even
add a comment to the end of a line of code, and everything after the `//` until
the next line starts is considered a comment.  If you need to add more than
one line of comments in a row, it must start with `/*` and end with `*/`

=== Operators

The most basic operator is `=`, the assignment operator. This operator is
used to *assign* a value to a variable.  Be careful not to confuse this
with `==`, the equals operator (discussed below).

----
    boolean javaIsTheBest = true;
    double twoAndAHalf = 2.5;
    int number = 5;
    String planet = "Earth";
----

Java includes basic math operators.  These include `+` (addition), `-`
(subtraction), `*` (multiplication), and `/` (division).  Just like in
regular math, you can also use brackets like `(` and `)` to make sure the
math operations happen in the right order.  Here are a few examples:

----
    int one = 1;
    int two = one + one;
    int four = two * two;
    int ten = 10;
    int six = ten - four;
    int five = ten / two;

    int minusTwo = ten - six * two;
    int eight = (ten - six) * two;
----

We can also compare numbers to each other using `>` (greater than), `<` (less
than), `>=` (greater than or equal to), `<=` (less than or equal to), and `==`
(equals). These operators return boolean values, 'true' and 'false'.

----
    boolean tenGreaterThanFive = 10 > 5;
    boolean twoEqualsTwo = 2 == 2;
    boolean zeroLessThanOne = 0 < 1;
    boolean threeLessOrEqualThree = 3 <= 3;
----

There are also the operators `||` (or) and `&&` (and), which are used with
booleans.

----
    boolean isRed = true;
    boolean isCar = true;
    boolean isRedCar = isRed && isCar;

    boolean hasDog = true;
    boolean hasCat = false;
    boolean hasPet = hasDog || hasCat;
----

The `==` operator from before can also be used with other literal types such
as booleans and chars, not just numbers.

----
    char letter1 = 'a';
    char letter2 = 'b';
    char letter3 = 'b';
    boolean same = letter2 == letter3;
    boolean different = letter1 == letter2;
    boolean compare = same == different;
----

There is one more common operator, which is `!` (not). This is used to
reverse the meaning of booleans.  In English, we can say it changes "true" to
mean "false" and "false" to mean "true".  Related is the operator `!=`, which
is like `!` and `==` combined. `a != b` is the same as `! (a == b)`.

----
    boolean yes = true;
    boolean no = ! yes;
----

=== Methods

Recall the declaration of the `introduce()` method in the Person class:

----
    public void introduce() {
----

As we already know, "introduce" is the name of the method. But what about the
rest of it?

`public` is the *visibility* of the method.  We refer to it as a *visibility
modifier*.  `public` is a keyword that means that this method can be used by
other classes.  Keep in mind that because it is not `static` an instance of
the Person class is still needed.

Another option for method or variable visibility is `private`.  This means
that only the class in which the method or variable is declared is allowed
to use it.  Let's add a private method to our Person class.

----
    public class Person {
        String firstName;
        String lastName;
        int age;

        public void introduce() {
            System.out.println(getIntroduction());
        }

        private String getIntroduction() {
            String intro = "Hi! My name is " + firstName + " " + lastName + ". I am " + age + " years old. I think Java is fun! :)";
            return intro;
        }
    }
----

This `getIntroduction()` method can be used from within the Person class, but
if we tried to add a line like `p.getIntroduction()` to our Devoxx4kids class
we would get an error.

There are two other options for visibility: `protected` and *default* (if we
declare a method or variable without a visibility keyword).  We won't worry
about what these mean for now.

You may have noticed another difference between the `introduce` and the
`getIntroduction` methods.  Look between the visibility keyword and the
method name.  One says `void` and the other says `String`.  These represent
the *return type* of the method.  A method's return type indicates what type
of thing the method produces, if any.  The `void` keyword is a special word
that indicates that the method does not produce anything.  While a visibility
modifier is not necessary when declaring a method, a return type must always
be present.  The return type can by any type, including primitives, classes
and arrays.  If the return type is not `void`, the method must also include
a *return statement*.

We have seen that a method declaration must have a *name*, a *return type*,
and may have a *visibility modifier* or the `static` keyword.  There is one
more part that a method may have: *parameters*.  You've actually already
seen this in the "main" method: it's the part that says `String[] args`.
Let's add a method with parameters to our Person class as an example.

----
public class Person {
        String firstName;
        String lastName;
        int age;
        
        public void introduce() {
            say(getIntroduction());
        }

        public void say(String statement) {
            System.out.println(statement);
        }
        
        private String getIntroduction() {
            String intro = "Hi! My name is " + firstName + " " + lastName + ". I am " + age + " years old. I think Java is fun! :)";
            return intro;
        }
    }
----

The new method `say` takes a single parameter of type String.  This means
when we call the method, we must include a String value in the brackets.
The value that we use is called the *argument*.  The argument can be a
literal (like `"Hello"`), a variable (like `lastName`), or another method
call, as long as the method returns the correct type.  In this example, we
use a call to the `getIntroduction()` method.

A method can take more than one parameter.  For example:

----
    // Takes two numbers and multiplies them
    public static double multiply(double first, double second) {
        return first * second;
    }
----

If we want to call a method like this, we must still use matching
arguments, like:

----
    double nine = multiply(4.5, 2.0);
----

As a reminder, a method declaration looks like this (with necessary parts
in bold):

+visibilitykeyword static **returntype name(**arguments**)**+

Everything here except for the `static` keyword will be different for each
method you write.

Aside from the declaration, it is important to look at the rest of the
method, which we call the *body*.  You'll notice that after the method
declaration is a `{`, which we call an opening curly brace, then one or
more lines of Java code, and finally a `}` which we call a closing curly
brace.  All of this is the body.  Each of the lines between the curly
braces is called a *statement*, and all statements in java must end in
a semicolon, like `;`.

Actually, there is a more general way to call this pattern of curly
braces surrounding several lines of code; it is called a *block*.  We
will see later on that this pattern is used by Java in other ways.

==== public static void main

Normally, programs need an "entry point", a place to start from at the very
beginning. In Java, this is the "main method". The main method declaration
always looks the same:

----
    public static void main(String[] args)
----

Now that we know what parameters are, you have probably guessed that you
can refer to the `args` variable in the main method.  But, where do the
values in this array come from?

When you run a java program, you can include additional words after the
class name, and these become the arguments when the main method is called.

That may be hard to understand, so let's make a small change to the main
method of our example to see how this works.

----
    public class Devoxx4kids {

        public static void main(String[] args) {
            Person p = new Person();
            p.firstName = "Mr.";
            p.lastName = "Java";
            p.age = 10;
            p.introduce();
            p.say(args[0]);
        }
    }
----

==== Constructors

Classes can also have a special kind of method called a 'constructor'. These
allow us to set the values of the variables in the class while an instance
is being created, and we can even do some other things in the constructor if
we want certain things to happen before the variable can be used. Even if
you do not create a constructor for a class, Java makes a default constructor
for you, that has no parameters.  We already used it earlier when we created
a Person instance. Let's now add a constructor to the Person class.

----
    // Person.java
    public class Person {
        private String firstName;
        private String lastName;
        private int age;

        // Constructor
        public Person(String firstName, String lastName, int age) {
            this.firstName = firstName;
            this.lastName = lastName;
            this.age = age;
        }

        public void introduce() {
            say(getIntroduction());
        }

        public void say(String statement) {
            System.out.println(statement);
        }

        private String getIntroduction() {
            String intro = "Hi! My name is " + firstName + " " + lastName + ". I am " + age + " years old. I think Java is fun! :)";
            return intro;
        }
    }
----

Notice that we've added the `private` keyword to the class variables
`firstName`, `lastName`, and `age`.  Because we now set these in the
constructor, they no longer need to be visible to other classes.

You may also have noticed the `this` keyword used.  This is a special word
that you can use in any non-static method.  It is how the class refers to
itself.

Constructor methods can only have a visibility modifier, a name, and
parameters. They never have return types and they cannot be static. Furthermore,
their name is always exactly the same as the name of their Class. Let's change
our example program to use this constructor.

----
    // Devoxx4kids.java
    public class Devoxx4kids {
        public static void main(String[] args) {
            Person p = new Person("Mr.", "Java", 10);
            p.introduce();
            p.say(args[0];
        }
    }
----

Now, when we compile and run the program, we can include arguments to the
main method on the command line, and it should look like this:

----
   $ javac Devoxx4kids.java Person.java
   $ java Devoxx4kids Goodbye
   Hi! my name is Mr. Java.  I am 10 years old.  I think java is fun! :)
   Goodbye
----

=== Basic I/O

I/O stands for Input/Output.  Input refers to ways to add information to
the program.  Output refers to ways to get information out of the program.
The simplest form of input is to read from the keyboard.  The simplest
form of output is to print information to the screen, which we have already
seen.  Let's look at this in more detail.
 
In the Person class, we have the `say` method, which contains the following.
----
    System.out.println(statement);
----

Here, "println" is the name of a method we are calling, and it has one String
parameter. 'println' takes the argument we give it and prints it to the screen.

Let's add a little more action. We can make the program ask us for input, do
something with it, and print out a result. We'll make it so the program takes
what we type in and makes everything lower case.

To be able to read things we type, the program will use something called Scanner.
Scanner is a class from the class library that comes as part of the JDK.  To use
Scanner, we need to "import" it.

----
    import java.util.Scanner;
----

"import" statements go at the very top of your program, before the class
declaration. Now we can use Scanner in our main method to get a line of text
from the user.

----
    Scanner sc = new Scanner(System.in);
    String line = sc.nextLine();
----

Now we have a Scanner variable called "sc" and a String variable called "line".
"line" holds the text that we gave as input on the keyboard.  We can even make
our Person instance say the line back as output.  This is how the program to
do so looks:

----
    import java.util.Scanner;

    public class Devoxx4kids {
        public static void main(String[] args) {
            Person p = new Person("Mr.", "Java", 10);
            p.introduce();
            System.out.println("What do you want me to say?");
            Scanner sc = new Scanner(System.in);
            String line = sc.nextLine();
            p.say(line);
        }
    }
----

We can expand this and make it so that we can enter a second line of text.

----
    import java.util.Scanner;

    public class Devoxx4kids {
        public static void main(String[] args) {
            Person p = new Person("Mr.", "Java", 10);
            p.introduce();
            System.out.println("What do you want me to say?");
            Scanner sc = new Scanner(System.in);
            String line = sc.nextLine();
            p.say(line);
            System.out.println("What else do you want me to say?");
            String line2 = sc.nextLine();
            say(line2);
        }
    }
----

=== Control Flow

So far, our program just runs in a straight line from top to bottom. What we
need is some way to have our program make decisions, and some way to automatically
do things more than once, so that we don't need to just write our code over and
over again.

==== Conditionals (if/else)

Conditionals allow our program to make decisions. The form of an `if`/`else`
statement in Java is this:

----
    if (condition) {
        // do something
    } else if (anotherCondition) {
        // do something else
    } else {
        // do another thing
    }
----

Notice that this type of syntax uses blocks, just like in a method.

"condition" and "anotherCondition" can be anything with type 'boolean'. If 'condition'
is 'true', then the first block of code is run, and the rest are skipped. If
'anotherCondition' is true and 'condition' is false, then only the second block
is run. If 'condition' and 'anotherCondition' are both false, then the last block
is run only. If both 'condition' and 'anotherCondition' are true, only the first
block is run still.

==== Loops

There are a few types of loop in Java. The most basic is the 'while' loop. This
loop is used with a boolean variable or expression, and it runs over and over
again, so long as the boolean is true.

----
    while (true) {
        // this loop will never end!
    }
----

We can use a 'while' loop along with 'if/else' and 'Scanner' from earlier
to make our program keep asking us to type input. Let's make a program that
adds up numbers until we give it 0.

----
    Scanner sc = new Scanner(System.in);
    int total = 0;
    boolean quit = false;
    while (! quit) {
        System.out.println("Give me a number:");
        int input = sc.nextInt();
        if (input == 0) {
            quit = true;
        }
        total = total + input;
    }
    System.out.println("The total is: " + total);
----

There are some special keywords we can use when working with loops: 'break' and
'continue'. 'break' causes the loop to stop completely, and 'continue' makes the
loop start from the top. We can use 'break' instead of the 'quit' variable.

----
    Scanner sc = new Scanner(System.in);
    int total = 0;
    while (true) { // looks like it will run forever...
        System.out.println("Give me a number:");
        int input = sc.nextInt();
        if (input == 0) {
            break; // but this makes it possible to stop the loop
        }
        total = total + input;
    }
    System.out.println("The total is: " + total);
----

What if we wanted to run our loop a specific number of times? We can do something
like this with a 'while' loop.

----
    int max = 5;
    int times = 0;
    int total = 2;
    while (times < max) {
        total = total * 2;
        times = times + 1;
    }
    System.out.println("total: " + total);
----

But now we have some extra variables that are only used for controlling the loop.
This is where the 'for' loop comes in. Here's a 'for' loop that does the same job
as the above 'while' loop:

----
    int total = 2;
    for (int i = 0; i < 5; i++) {
        total = total * 2;
    }
    System.out.println("total: " + total);
----

Notice that inside the parentheses, there are three parts, separated by semicolons.
The first part, "int i = 0", declares our loop variable(s). The second part,
"i < 5" defines when the loop will stop. So long as i is less than 5, the loop will
keep running. The last part, 'i++', is shorthand for "i = i + 1". It means that the
loop variable 'i' will become larger by one at the end of the loop.

The last loop we'll cover in this section is the 'do-while' loop. This is just a
special kind of 'while' loop. Examine this 'while' loop:

----
    while (false) {
        System.out.println("Hello!");
    }
----

Since 'while' loops run over and over as long as the boolean condition is true,
and this one is always false, this 'while' loop will never actually run, not even
once. The 'do-while' loop is just a 'while' that will always run at least once.

----
    do {
        System.out.println("Hello!");
    } while (false);
----

Try both of these out and see for yourself that the `while` loop does not print
"Hello!", and the 'do-while' prints it exactly once.

In our example program, we can use a loop to keep our Person saying things until
we provide a String with length 0 as input:

----
    import java.util.Scanner;

    public class Devoxx4kids {

        public static void main(String[] args) {
            Person p = new Person("Mr.", "Java", 10);
            p.introduce();
            Scanner sc = new Scanner(System.in);
            String line = null;
            while (line == null || line.length() > 0) {
                System.out.println("What do you want me to say? ");
                line = sc.nextLine();
                if (line.length > 0) {
                    p.say(line);
                }
            }
        }

    }
----

In addition to the `while` loop, we've also used a new keyword: `null`.  This
is a special keyword for non-primitive variables, and it means that the
variable does not refer to any instance.

