= Minecraft Modding using Spigot
:toc:
:toc-placement!:

This workshop shows how to get started with server-side Minecraft modding using Spigot.

toc::[]

[[Requirements]]
== Requirements

* A paid Minecraft account
* A Mac or a Windows computer

[[Download]]
== Download and Install

. **JDK:** Download and install JDK from http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
. **NetBeans:** Download and install NetBeans from https://netbeans.org/downloads/, click the download button below the "`Java SE`" column
. **Spigot:** Download Spigot 1.8 from http://getspigot.org/spigot18/spigot_server.jar

Follow the instructions for Mac or windows as explained below.

=== Mac
. In Finder, go to Applications, Utilities, and double click on Terminal
. Change directory to Desktop: `cd Desktop`
. Make a new "`spigot`" directory: `mkdir spigot`
. Change to the directory: `cd spigot`
. Copy the spigot server file to the "`spigot`" directory: `cp ~/Downloads/spigot_server.jar .`
** The spigot server file is usually in the "`Downloads`" directory, but if it is not, you can manually copy it using Finder
. Run the spigot server file: `java -jar spigot_server.jar`
** The server will stop and you will see a message like `[15:24:34 INFO]: You need to agree to the EULA in order to run the server. Go to eula.txt for more info.`
. Set the EULA to true by giving this command in the "`spigot`" directory in Terminal: `sed s/false/true/g eula.txt | tee eula.txt`
. Start the server again: `java -jar spigot_server.jar`

=== Windows
. Open a Command Prompt as explained at http://windows.microsoft.com/en-us/windows-vista/open-a-command-prompt-window
. Change directory to Desktop: `cd Desktop`
. Make a new "`spigot`" directory: `mkdir spigot`
. Change to the directory: `cd spigot`
. Using File Explorer, copy the "`spigot_server.jar`", which is usually in the "`Downloads`" directory, into the new "`spigot`" directory
. In Command Prompt, in the "`spigot`" directory, run the spigot server file: `java -jar spigot_server.jar`
** The server will stop and you will see a message like `[15:24:34 INFO]: You need to agree to the EULA in order to run the server. Go to eula.txt for more info.`
. Open up the "`eula.txt`" file by double-clicking on it. Change the text "`eula=false`" to "`eula=true`" and save it
. Start the server again: `java -jar spigot_server.jar`

=== Verify

This step is important because it makes sure that your server is working correctly.

. Open up the Minecraft 1.8.9 client
. Click on the "`Multiplayer`" button
. Click "`Add server`"
. In the "`Server Address`" box, type in `localhost`
** The server name can be whatever you want
. Click "`Done`"
. Double-click on the server to connect
** The server should say "`A Minecraft Server`" under the server name


=== Troubleshooting

. If the server stops because of the EULA again, make sure that you set it to true and save the file.
. If you see a red message on the server in Minecraft that says "`Can't connect to server.`", your server is not running. Start it again by using `java -jar spigot_server.jar` and click the "`Refresh`" button to see if it works.

[[First_Plugin]]
== Creating your First Plugin

This plugin will be a simple plugin that will print a message in your server console when it is enabled.

To make a plugin, we will be using an archetype. An archetype is like a cookie cutter, and in this case, it will make all of the essential plugin files for you.

=== Gameplay

[[Crafting_Experience]]
== Crafting Experience

Experience can be hard to get in normal Minecraft, and it is very useful once you get it. This plugin aims to make experience collection easier by giving the player experience whenever he or she crafts an item.

=== Gameplay

. Get a Crafting Table from your inventory
. Place down the Crafting Table in the world
. Get out three Cobblestone blocks from your inventory
. Open up the Crafting Table by right-clicking on it
. Place the three Cobblestone blocks in a row in the Crafting Table inventory
. Take out the Cobblestone Slabs that appear on the right
. An experience bottle should fall where you are and give you some experience
** If you don't see the experience level at the bottom, change your gamemode to Survival by typing the command `/gamemode 0`

[[Cat_Arrows]]
== Cat Arrows

Normal bows are a bit boring, because they do exactly what bows are supposed to do. Now, with this plugin, you can make bows shoot out cats instead of arrows!

=== Gameplay

. Get out a Bow from your inventory
. Hold down right-click to charge the bow until it starts shaking
. Release right-click to fire the bow, and instead of firing an arrow, it should fire a cat
. Get out a Power V Enchanted Book and a Flame I Enchanted Book from your inventory
. Get out two more Bows from your inventory, along with an Anvil
. Place down the Anvil and right-click on it to open it
. Place one of the Bows in the right-hand slot and place the Power V Enchanted Book in the slot next to it
. Take out the enchanted Bow that appears on the right
. Place the other Bow in the right-hand slot and place the Flame I Enchanted Book in the slot next to it
. Take out the enchanted Bow that appears on the right
. Shoot the Bow with Power V to launch the cat farther, and shoot the Bow with Flame I to launch flaming cats

[[Ore_Shrooms]]
== Ore Shrooms

Valuable ores like diamonds and emeralds can be even harder to come by than experience. Mushrooms, however, are easy to make, because you can grow one small mushroom into a giant one. With this plugin, giant mushrooms will not only contain mushroom blocks, but they will also have diamond, emerald, gold, and iron blocks.

=== Gameplay

. Get out a Red Mushroom, a Brown Mushroom, a Bone Meal, and a Mycelium from your inventory
. Place down two Mycelium about 10 blocks away from each other
. Place the Red Mushroom on one Mycelium and the Brown Mushroom on the other Mycelium
. Right-click on both mushrooms with Bone Meal
. It may take a few tries, but the mushrooms will eventually grow into huge mushrooms
. The huge mushrooms should have lots of ore blocks on them, as well as some huge mushroom blocks