= Minecraft Modding using Forge

To get started, follow the instructions for http://www.minecraftforge.net/wiki/Installation/Source[downloading and installing Java and Forge].

== The Main File

To start modding, we need a main file. This file will register all of our mods so that they actually function in the game. To make this main file, first you need to make a new package. Click on the arrow next to the "Minecraft" folder in the left side of your window. Then, right click on "src/main/java" and select New > Package. Name it `org.devoxx4kids.forge.mods`.

In this package, create a new class called `MainMod.java`. To do this, right click on the new package you created and select New > Class. Name it `MainMod`. The middle of your screen will show its code. Replace all of the code with the code in <<Setting_Up_The_Main_File>>.

[[Setting_Up_The_Main_File]]
.Set up the main file
====
[source, java]
----
package org.devoxx4kids.forge.mods;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLInitializationEvent;

@Mod(modid = MainMod.MODID, version = MainMod.VERSION)
public class MainMod {
	public static final String MODID = "MyMods";
	public static final String VERSION = "1.0";

	@EventHandler
	public void init(FMLInitializationEvent event) {

	}
}
----
====

Your main file is now ready to go.

== Chat Items

**Purpose:** To make the player receive items when he/she says a certain word or phrase in a chat message.

**Instructions:** In your new package, `org.devoxx4kids.forge.mods`, make a new file called `ChatItems.java`. Replace its code with <<Chat_Items_Code>>.

[[Chat_Items_Code]]
.Chat Items code
====
[source, java]
----
package org.devoxx4kids.forge.mods;

import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.event.ServerChatEvent;
import cpw.mods.fml.common.eventhandler.SubscribeEvent;

public class ChatItems {
	
	@SubscribeEvent
	public void giveItems(ServerChatEvent event){
		if (!(event.message.contains("potato"))) {
			return;
		}
		
		event.player.inventory.addItemStackToInventory(new ItemStack(Items.potato, 64));
	}
}
----
====

Register your mod in the main file by using the line shown in <<Chat_Items_Registering>>. The line should go between the two brackets after the line that says `init()`.

[[Chat_Items_Registering]]
.Chat Items registering
====
[source, java]
----
MinecraftForge.EVENT_BUS.register(new ChatItems());
----
====

Your main file should now look like <<Main_File_After_Register>>.

[[Main_File_After_Register]]
.Main file after registering Chat Items
====
[source, java]
----
package org.devoxx4kids.forge.mods;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLInitializationEvent;

@Mod(modid = MainMod.MODID, version = MainMod.VERSION)
public class MainMod {
	public static final String MODID = "MyMods";
	public static final String VERSION = "1.0";

	@EventHandler
	public void init(FMLInitializationEvent event) {
		MinecraftForge.EVENT_BUS.register(new ChatItems());
	}
}
----
====

**Gameplay:**

. Press ``T'' to open up the chat window
. Type in any message that contains the word ``potato''
. You should receive one stack (one stack = 64 items) potatoes

== Dragon Spawner

**Purpose:** To spawn an Ender Dragon every time a player places a Dragon Egg block.

**Instructions:** In the package `org.devoxx4kids.forge.mods`, make a new class called `DragonSpawner` and replace its code with the code shown in <<Dragon_Spawner_Code>>.

[[Dragon_Spawner_Code]]
.Dragon Spawner code
====
[source, java]
----
package org.devoxx4kids.forge.mods;

import net.minecraft.entity.boss.EntityDragon;
import net.minecraft.init.Blocks;
import net.minecraftforge.event.world.BlockEvent.PlaceEvent;
import cpw.mods.fml.common.eventhandler.SubscribeEvent;

public class DragonSpawner {
	
	@SubscribeEvent
	public void spawnDragon(PlaceEvent event) {
		if (event.block != Blocks.dragon_egg) {
			return;
		}
		
		event.world.setBlock(event.x, event.y, event.z, Blocks.air);
		EntityDragon dragon = new EntityDragon(event.world);
		dragon.setLocationAndAngles(event.x, event.y, event.z, 0, 0);
		event.world.spawnEntityInWorld(dragon);
	}

}
----
====

Then, register it like you did with Chat Items, but use the line of code shown in <<Dragon_Spawner_Registering>>.

[[Dragon_Spawner_Registering]]
.Dragon Spawner registering
====
[source, java]
----
MinecraftForge.EVENT_BUS.register(new DragonSpawner());
----
====

**Gameplay:**

. Use the command "/give <your player name> 122" to give yourself a dragon egg
. Place down the dragon egg, and an Ender Dragon should spawn

The player name will not be your normal player name, it will be a Forge-generated player name. Check your chat window to see what your player name is.

== Overpowered Iron Golems

**Purpose:** To add helpful potion effects to Iron Golems when they spawn in the world.

**Instructions:**

In your package, make a new class called `OverpoweredIronGolems` and replace its contents with <<Iron_Golems_Code>>.

[[Iron_Golems_Code]]
.Overpowered Iron Golems code
====
[source, java]
----
package org.devoxx4kids.forge.mods;

import net.minecraft.entity.EntityLiving;
import net.minecraft.entity.monster.EntityIronGolem;
import net.minecraft.potion.PotionEffect;
import net.minecraftforge.event.entity.EntityJoinWorldEvent;
import cpw.mods.fml.common.eventhandler.SubscribeEvent;

public class OverpoweredIronGolems {
	
	@SubscribeEvent
	public void golemMagic(EntityJoinWorldEvent event) {
		if (!(event.entity instanceof EntityIronGolem)) {
			return;
		}
		
		EntityLiving entity = (EntityLiving) event.entity;
		entity.addPotionEffect(new PotionEffect(1, 1000000, 5));
		entity.addPotionEffect(new PotionEffect(5, 1000000, 5));
		entity.addPotionEffect(new PotionEffect(10, 1000000, 5));
		entity.addPotionEffect(new PotionEffect(11, 1000000, 5));
	}

}
----
====

Then, register the class using the line shown in <<Iron_Golems_Register>>.

[[Iron_Golems_Register]]
====
[source, java]
----
MinecraftForge.EVENT_BUS.register(new OverpoweredIronGolems());
----
====

**Gameplay:**

. Spawn an Iron Golem by using the command "/summon VillagerGolem".
. Spawn some hostile mobs near the Iron Golem

The golem should move towards them to kill them. Normally, Iron Golems move slowly, but with the speed effect from the mod, they should move very fast.

== Creeper Spawn Alert

**Purpose:** To alert all players when a creeper spawns.

**Instructions:** In your package, make a new class called `CreeperSpawnAlert`. Replace its contents with <<Creeper_Spawn_Code>>.

[[Creeper_Spawn_Code]]
.Creeper Spawn Alert code
====
[source, java]
----
package org.devoxx4kids.forge.mods;

import java.util.List;

import net.minecraft.entity.monster.EntityCreeper;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.util.ChatComponentText;
import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.event.entity.EntityJoinWorldEvent;
import cpw.mods.fml.common.eventhandler.SubscribeEvent;

public class CreeperSpawnAlert {

	@SubscribeEvent
	public void sendAlert(EntityJoinWorldEvent event) {
		if (!(event.entity instanceof EntityCreeper)) {
			return;
		}

		List players = event.entity.worldObj.playerEntities;

		for (int i = 0; i < players.size(); i++) {
			EntityPlayer player = (EntityPlayer) players.get(i);
			player.addChatMessage(new ChatComponentText(
					EnumChatFormatting.GREEN + "A creeper has spawned!"));
		}
	}

}
----
====

Register it using the line in <<Creeper_Spawn_Registering>>.

[[Creeper_Spawn_Registering]]
.Creeper Spawn Alert registering
====
[source, java]
----
MinecraftForge.EVENT_BUS.register(new CreeperSpawnAlert());
----
====

**Gameplay:**

. Make sure you are not on peaceful mode.
. Set the time to night time ("/time set night") 

You should get a bunch of messages saying "A creeper has spawned!" in light green letters. One of these messages is sent to you every time a creeper spawns.

== Sharp Snowballs

**Purpose:** To turn all snowballs into arrows so that they can hurt entites.

**Instructions:** In your package, create a new class called `SharpSnowballs`. Replace its code with <<Snowballs_Code>>.

[[Snowballs_Code]]
.Sharp Snowballs code
====
[source, java]
----
package org.devoxx4kids.forge.mods;

import net.minecraft.entity.Entity;
import net.minecraft.entity.projectile.EntityArrow;
import net.minecraft.entity.projectile.EntitySnowball;
import net.minecraft.world.World;
import net.minecraftforge.event.entity.EntityJoinWorldEvent;
import cpw.mods.fml.common.eventhandler.SubscribeEvent;

public class SharpSnowballs {

	@SubscribeEvent
	public void replaceSnowballWithArrow(EntityJoinWorldEvent event) {
		Entity entity = event.entity;
		World world = entity.worldObj;

		if (!(entity instanceof EntitySnowball)) {
			return;
		}

		if (!world.isRemote) {
			EntityArrow arrow = new EntityArrow(world);
			arrow.setLocationAndAngles(entity.posX, entity.posY, entity.posZ,
					0, 0);
			arrow.motionX = entity.motionX;
			arrow.motionY = entity.motionY;
			arrow.motionZ = entity.motionZ;

			arrow.posX += arrow.motionX;
			arrow.posY += arrow.motionY;
			arrow.posZ += arrow.motionZ;

			world.spawnEntityInWorld(arrow);
			entity.setDead();
		}
	}

}
----
====

Register the new class using the line in <<Snowballs_Registering>>.

[[Snowballs_Registering]]
.Sharp Snowballs registering
====
[source, java]
----
MinecraftForge.EVENT_BUS.register(new SharpSnowballs());
----
====

**Gameplay:**

. Get a Snowball item from your inventory
. Right click with it to throw it
. It should turn into an arrow

You can also spawn Snow Golems by placing a pumpkin on top of a tower of two Snow blocks. The Snow Golem will act as a turret, shooting out snowballs that turn into arrows.

== Rain Water

**Purpose:** To place water at the feet of entities when it is raining.

**Instructions:** In your package, create a new class called `RainWater` and replace its contents with <<Rain_Code>>.

[[Rain_Code]]
.Rain Water code
====
[source, java]
----
package org.devoxx4kids.forge.mods;

import net.minecraft.entity.Entity;
import net.minecraft.init.Blocks;
import net.minecraft.world.World;
import net.minecraftforge.event.entity.living.LivingEvent.LivingUpdateEvent;
import cpw.mods.fml.common.eventhandler.SubscribeEvent;

public class RainWater {

	@SubscribeEvent
	public void makeWater(LivingUpdateEvent event) {
		Entity entity = event.entity;
		World world = entity.worldObj;
		int x = (int) Math.floor(entity.posX);
		int y = (int) Math.floor(entity.posY);
		int z = (int) Math.floor(entity.posZ);

		if (!entity.worldObj.isRaining()) {
			return;
		}

		for (int i = y; i < 256; i++) {
			if (world.getBlock(x, i, z) != Blocks.air) {
				return;
			}
		}
		
		if (world.isRemote && !world.getBlock(x, y - 1, z).isBlockNormalCube()) {
			return;
		}

		if (!world.isRemote) {
			world.setBlock(x, y, z, Blocks.water, 5, 1);
		}
	}

}
----
====

Then, register it using the line shown in <<Rain_Registering>>.

[[Rain_Registering]]
.Rain Water registering
====
[source, java]
----
MinecraftForge.EVENT_BUS.register(new RainWater());
----
====

**Gameplay:**

. Use the command "/weather rain" to make the weather rainy
. Start moving, and water should be placed wherever you go, but it will disappear quickly

== Sharing Your Mods

Open up your computer's command prompt. Navigate to your Forge folder. Then, type the command `gradlew build`. On a Mac it may be `./gradlew build`. After the process completes, navigate to the "build" folder, then the "libs" folder inside that. In that folder, there should be a .jar file called `modid-1.0.jar`. This .jar file is all of your mods. 

To install your mod on your Minecraft launcher, follow the instructions at http://www.minecraftforge.net/wiki/Installation/Universal.

== Tips

* When changing an item or block, delete the current item/block and press `Ctrl + Space` to pull up a list of items and blocks that are availible.
